apiVersion: apps/v1
kind: Deployment
metadata:
  name: metfamily-deployment
  labels:
    app: metfamily
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: metfamily
  template:
    metadata:
      labels:
        app: metfamily
    spec:
      containers:
      - name: metfamily
        image: korseby/metfamily
        ports:
        - containerPort: 3838

---

apiVersion: v1
kind: Service
metadata:
  name: metfamily-service
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
  labels:
    app: metfamily
spec:
  selector:
    app: metfamily
  ports:
  - port: 80
    targetPort: 3838
    protocol: TCP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: metfamily-traefik
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: metfamily.10.22.12.2.nip.io
    http:
      paths:
      - backend:
          serviceName: metfamily-service
          servicePort: 80
        path: /
