apiVersion: apps/v1
kind: Deployment
metadata:
  name: metfamily-deployment
  labels:
    app: metfamily
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metfamily
  template:
    metadata:
      labels:
        app: metfamily
    spec:
      containers:
      - name: metfamily
        image: sneumann/metfamily
        ports:
        - containerPort: 3838
        resources:
          limits:
            cpu: "4"
            memory: 16G
          requests:
            cpu: "2"
            memory: 8G
        volumeMounts:
        - name: thoms-vol
          mountPath: /srv/shiny-server/inst/data/classifier/
      volumes:
      - name: thoms-vol
        nfs:
          server: 192.168.0.20
          path: /vol/R/shiny/srv/shiny-server/MetFam/MetFamily/inst/data/classifier/

---

apiVersion: v1
kind: Service
metadata:
  name: metfamily-service
  labels:
    app: metfamily
spec:
  selector:
    app: metfamily
  ports:
  - port: 80
    targetPort: 3838
    protocol: TCP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: metfamily-nginx
  annotations:
     nginx.ingress.kubernetes.io/affinity: cookie
     nginx.ingress.kubernetes.io/proxy-body-size: "500m"
     nginx.ingress.kubernetes.io/session-cookie-path: "/MetFamily/"
     nginx.ingress.kubernetes.io/affinity: "cookie"
     nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
     nginx.ingress.kubernetes.io/proxy-write-timeout: "600"
     nginx.ingress.kubernetes.io/rewrite-target: /$2

spec:
  rules:
  - host: "msbi.ipb-halle.de"
    http:
      paths:
      - backend:
          serviceName: metfamily-service
          servicePort: 80
        path: /MetFamily(/|$)(.*)
