apiVersion: apps/v1
kind: Deployment
metadata:
  name: metfamily-dev-deployment
  labels:
    app: metfamily-dev
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: metfamily-dev
  template:
    metadata:
      labels:
        app: metfamily-dev
    spec:
      containers:
      - name: metfamily-dev
        image: korseby/metfamily-dev
        ports:
        - containerPort: 3838

---

apiVersion: v1
kind: Service
metadata:
  name: metfamily-dev-service
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/preserve-host: "true"
    ingress.kubernetes.io/affinity: 'cookie'
  labels:
    app: metfamily-dev
spec:
  selector:
    app: metfamily-dev
  ports:
  - port: 80
    targetPort: 3838
    protocol: TCP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: metfamily-dev-traefik
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: metfamily-dev.10.22.12.2.nip.io
    http:
      paths:
      - backend:
          serviceName: metfamily-dev-service
          servicePort: 80
        path: /
